"""add_transport_models

Revision ID: f22c97884a59
Revises: 4e19b2818c6c
Create Date: 2026-07-09 15:04:33.403016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22c97884a59'
down_revision: Union[str, Sequence[str], None] = '4e19b2818c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stadium_id', sa.Uuid(), nullable=False),
    sa.Column('lot', sa.String(), nullable=False),
    sa.Column('available_spots', sa.Integer(), nullable=True),
    sa.Column('total_spots', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stadium_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('next_arrival', sa.String(), nullable=True),
    sa.Column('wait_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_options')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
